.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctl-addmodule 1 "February 2013" Linux "User Manuals"

.\"**********************************************************************

.SH NAME
ctl-addmodule \- adds modules to a specific cluster   
.SH SYNOPSIS
.B ctl-addmodule
.RB <
.IR manifestfile 
.RB >

 

.\" **********************************************************************

.SH DESCRIPTION

.BR ctl-addmodules
is executed in order to add modules to a clusters module's list

.\".SH OPTIONS
.\".TP
.\"blubber

.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1)
.BR ctl-getmodule


