.TH ctl-genmanifest 1  "August 2013" Linux "User Manuals"

.\"**********************************************************************

.SH NAME
ctl-genmanifest \- builds manifest data from components   
.SH SYNOPSIS
.B ctl-genmanifest
.RB \| \-n
.IR name \|
.RB \| \-c
.IR interface \|
.RB \| \-i
.IR component \|
.RB [\| \-\-doc=
.IR documentfile \|] 
.RB [\| \-h
.IR hostname \|]
.RB [\| \-p
.IR port \|]
.RB [\| \-u
.IR user \|]
.RB [\| \-v \|]
.RB [\| \-\-version \|]
.\" **********************************************************************

.SH DESCRIPTION

.BR ctl-genmanifest
generates manifest data from a specified component and packs it for practical use on the ctlweb-system.

.SH OPTIONS
.TP
.BI \-n\ \fIname \fR,\ \fB\-\-name=\fIname
TODO
.TP
.BI \-c\ \fIinterface \fR,\ \fB\-\-ci=\fIinterface
Specifies the interface of the component
.TP
.BI \-i\ \fIcomponent  \fR,\ \fB\-\-impl=\fIcomponent
Specifies the actual component
.TP
.BI \fB\-\-doc=\fIdocument
Optional to give a name to your generated document. Defaults to "Component.txt"
.TP
.BI \-h\ \fIhostname \fR,\ \fB\-\-hostname=\fIhostname
Specifies the hostname of the component
.TP
.BI \-p\ \fIport \fR,\ \fB\-\-port=\fIport
Specifies the port
.TP
.BI \-u\ \fIuser \fR,\ \fB\-\-user=\fIuser
Specifies the user to be included in the manifest
.TP
.BR \-v ", " \-\-verbose
Increases verbosity
.TP
.BI \-\-version
Prints the installed version of this command

.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1)



