.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctl 1 "MARCH 1995" Linux "User Manuals"
.SH NAME
ctl \- execute commands on dedicated clusters, generate manifest data~ 
.SH SYNOPSIS
.br
.B ctl-web
.RB [\| \-a 
.IR id \|]
.RB [\| \-k 
.IR publickey \|]
.RB [\| \-r
.IR id \|]
.RB [\| \-o \|]
.SH DESCRIPTION
.B ctl-web
.SH OPTIONS
.BI \-a\  id \fR,\ \fB\-\-add= id
.IP "-c config-file"
.IR /etc/foo.conf .
.SH FILES
.SH ENVIRONMENT
.SH DIAGNOSTICS
 
.SH BUGS
.SH AUTHOR
Jens Schweikhardt <howto at schweikhardt dot net>
.SH "SEE ALSO"
.BR bar (1),
.BR foo (5),
.BR xyzzy (1)



