.TH ctl-register 1 "August 2013" Linux "User Manuals"
.SH NAME
ctl-register \- register or delete a user on/from a cluster  
.SH SYNOPSIS
.br
.\" ctl-register section
.B ctl-register 
.RB [\| \-h \|]
{add,remove,overview}
.br
.\" ctl-register add section
.B ctl-register add
.RB [\| \-h \|]
.RB [\| \-c
.IR CONFIG \|]
.RB [\| \-v \|]
.RB \| \-k 
.IR KEY \|
.IR USER
.br
.\" ctl-register remove section
.B ctl-register remove
.RB [\| \-h \|]
.RB [\| \-c
.IR CONFIG \|]
.RB [\| \-v \|]
.IR USER
.br
.\" ctl-register overview section
.B ctl-register overview
.RB [\| \-h \|]
.RB [\| \-c 
.IR CONFIG \|] 
.RB [\| \-v \|]
.RB [\| \-t
.IR TIMESTAMP \|]

.SH DESCRIPTION
.B ctl-register
usually is executed by the ctlweb-system itself in order to register or delete
a user on/from
a specific cluster. Under special circumstances, however, it can be issued by a
system administrator to manually add/remove a user.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Prints a help message with all required/optional arguments and their meanings
.TP
.BI \-c\ \fICONFIG \fR,\ \fB\-\-config\ \fICONFIG
If this option is not given, a default config file will be used
.TP
.BR \-v ", " \-\-verbose
Increases verbosity
.TP
.BI \-k\  KEY \fR,\ \fB\-\-key\ \fIKEY
Adds the specified Public Key of a user to a cluster.
.TP
.BI \-t\  TIMESTAMP \fR,\ \fB\-\-timestamp\ \fITIMESTAMP
Shows only user newer than the timestamp


.\" .SH FILES

.\" .SH ENVIRONMENT

.\".SH DIAGNOSTICS
 
.\" .SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1),
.BR ctl-web (1),
.BR ctl-webinteractive(1)
