.TH ctl-webinteractive 1 "August 2013" Linux "User Manuals"
.SH NAME
ctl-webinteractive \- frontend for ctl-web, ctl-register, ctl-component  

.SH SYNOPSIS
ctl-webinteractive

.SH DESCRIPTION
.B ctl-webinteractive
is a sort of frontend for the most important commands: ctl-web, ctl-register,
ctl-component. It will guide the user through all necessary steps without the
need of knowledge of the exact syntax of the commands
.\".SH OPTIONS

.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl-init (1),
.BR ctl-web (1),
.\".BR ctl-runcgi (1),
.BR ctl-register(1),
.BR ctl-component(1)



