.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctl-web 1 "June 2013" Linux "User Manuals"
.SH NAME
ctl-web \- Grants or revokes access for ctlweb frontends on clusters  
.SH SYNOPSIS
.br
.\" ctl-web section
.B ctl-web 
.RB [\| \-h \|]
{add,remove,overview}
.br
.\" ctl-web add section
.B ctl-web add
.RB [\| \-h \|]
.RB [\| \-c
.IR CONFIG \|]
.RB [\| \-v \|]
.RB \| \-u \|
.IR URL \|
.RB \| \-k 
.IR KEY \|
.br
.\" ctl-web remove section
.B ctl-web remove
.RB [\| \-h \|]
.RB [\| \-c
.IR CONFIG \|]
.RB [\| \-v \|]
.RB \| \-u \|
.IR URL \|
.br
.\" ctl-web overview section
.B ctl-web overview
.RB [\| \-h \|]
.RB [\| \-c 
.IR CONFIG \|] 
.RB [\| \-v \|]
.RB [\| \-t
.IR TIMESTAMP \|]

.SH DESCRIPTION
.B ctl-web
does add ctlweb frontends to a cluster. This command also offers the
deletion of them and can provide an entire overview over all registered
frontends on a specific cluster.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Prints a help message with all required/optional arguments and their meanings
.TP
.BI \-c\ \fICONFIG \fR,\ \fB\-\-config\ \fICONFIG
If this option is not given, a default config file will be used
.TP
.BR \-v ", " \-\-verbose
Increases verbosity
.TP
.BI \-u\  URL \fR,\ \fB\-\-url\ \fIURL
Specifies the URL to be added/removed
.TP
.BI \-k\  KEY \fR,\ \fB\-\-key\ \fIKEY
Adds the specified Public Key to a cluster.
.TP
.BI \-t\  TIMESTAMP \fR,\ \fB\-\-timestamp\ \fITIMESTAMP
Shows only ctlweb frontends newer than the timestamp


.\" .SH FILES

.\" .SH ENVIRONMENT

.\".SH DIAGNOSTICS
 
.\" .SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1),
.BR ctl-register (1)
