.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctl 1 "January 2013" Linux "User Manuals"
.SH NAME
ctl-runcgi \- starts a cgi environment for the administrator
.SH SYNOPSIS
.B ctl-runcgi
.RI [\| host \|]
.\" Description of ctlweb section
.SH DESCRIPTION
.B ctl-runcgi
starts a cgi environment for a ctlweb instance in order to administrate it 
.SH OPTIONS
.TP
\fP[\fIhost\fP] 
Specify on which host adress a cgi environment should be started

.\".SH FILES

.\".SH ENVIRONMENT


.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1)
