.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctl 1 "January 2013" Linux "User Manuals"
.SH NAME
ctl \- execute commands on dedicated clusters, generate manifest data~ 
.\".SH SYNOPSIS

.SH DESCRIPTION
.B ctlweb
is a family of tools to complement the Website ctlweb.
Further information is available at the specific manpages of each command.
.br
.B ctlinit
.br
.B ctl-web
.br 
.B ctl-runcgi
.br
.B ctl-register
.br  
.B ctl-genmanifest
.\".SH OPTIONS

.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctlinit (1),
.BR ctl-web (1),
.BR ctl-runcgi (1),
.BR ctl-register(1),
.BR ctl-genmanifest(1)



