.TH ctl 1 "September 2013" Linux "User Manuals"
.SH NAME
ctl \- execute commands on dedicated clusters, generate manifest data~ 
.\".SH SYNOPSIS

.SH DESCRIPTION
.B ctl
is a family of tools to complement the Website ctlweb.
Further information is available at the specific manpages of each command and
is thus recommended to read 
.br
.B ctl-init
.br
.B ctl-web
.br 
.\".B ctl-runcgi
.\".br
.B ctl-register
.br  
.B ctl-genmanifest
.br
.B ctl-component
.br
.B ctl-webinteractive
.br
.B ctl-build-component
.\".SH OPTIONS

.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl-init (1),
.BR ctl-web (1),
.\".BR ctl-runcgi (1),
.BR ctl-register(1),
.BR ctl-genmanifest(1),
.BR ctl-component(1),
.BR ctl-webinteractive(1),
.BR ctl-build-component(1)
