.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ctlinit 1 "January 2013" Linux "User Manuals"
.SH NAME
ctlinit \- get your module started 
.SH SYNOPSIS
.\" Just the ctlinit command 
.B ctlinit
.RI [\| module \|] 
.SH DESCRIPTION
.B ctlinit
logs in yourself on a cluster and starts your desired algorithm, program etc.  
.SH OPTIONS
.TP
\fP[\fImodule\fP]
Put the name of your module you want to start here
.\".SH FILES

.\".SH ENVIRONMENT

.\".SH DIAGNOSTICS

.\".SH BUGS

.SH AUTHOR
Jörn Hameyer <>
.SH "SEE ALSO"
.BR ctl (1),





